# Azure Pipelines YAML file
# Build and deploy TemplateApi project to Azure App Service

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '<azure-subscription-name>'
  # Name of the Azure Resource Group to deploy resources to
  resourceGroupName: '<resource-group-name>'
  # Name of the App Service Plan to use for the App Service
  appServicePlanName: '<app-service-plan-name>'
  # Name of the App Service to deploy the web app to
  webAppName: '<app-service-name>'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'artifact-name'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    displayName: Deploy Web App
    environment: 'webapp'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'artifact-name'
              downloadPath: '$(System.ArtifactsDirectory)/drop'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              WebAppName: $(webAppName)
              packageForLinux: '$(System.ArtifactsDirectory)/drop/TemplateApi.zip'
              ResourceGroupName: $(resourceGroupName)
              SlotName: 'production'
              # uncomment the following line if you want to deploy to a specific slot
              # slotName: '<slot-name>'
              DeploymentMode: 'Auto'
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              appName: $(webAppName)
              resourceGroupName: $(resourceGroupName)
              action: 'RestartAzureWebApp'
