name: HangMan Project Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.IshmaelPrimus }}
          password: ${{ secrets.dckr_pat_qlmNxKB3lJ-qg2foMLgNnkuE-z4 }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ishmaelprimus }}/hangman:0.0.1
