name: Continuous Integration HangMan Game

# This on clause specifies which event this pipeline/workflow will run
on: 
  push: 
    branches: 
      - main #run whenever there is a push event to main branch
  pull_request:
    branches: 
      - main # run whenever there is a pull request to main branch
  workflow_dispatch: # you can manually trigger this workflow

jobs:
  build:
    login:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout git repo
          uses: actions/checkout@v3
        
        - name: Login to DockerHub
          uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
          
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
            context: HangMan-Prj/
            file: HangMan-Prj/Dockerfile
            push: true
            tags: ishmaelprimus/hangman:0.0.2
          
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v2
          with:
            name: .net-app
            path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
